CREATE DATABASE IF NOT EXISTS school;

USE school;

CREATE TABLE IF NOT EXISTS Course (
CourseID INT NOT NULL,
Name VARCHAR(100) NOT NULL,
StudyArea VARCHAR(50) NOT NULL,
PRIMARY KEY (CourseID));

CREATE TABLE IF NOT EXISTS Student (
StudentID INT NOT NULL,
CourseID INT NOT NULL,
Name VARCHAR(100) NOT NULL,
Created DATE NOT NULL,
Age INT NOT NULL,
CPF VARCHAR(11) NOT NULL,
PRIMARY KEY (StudentID),
FOREIGN KEY (CourseID) REFERENCES Course (CourseID));



